### ISSUE TITLE
Issue building bootloader for ardupilot

### ISSUE THREAD

**Issue by KarolNi** [dronecan/libcanard#1]
I was trying to build bootloader for experimental AP_Periph board, but build was failing.
```
Traceback (most recent call last):
  File "/vagrant/modules/DroneCAN/libcanard/dsdl_compiler/libcanard_dsdlc", line 63, in <module>
    from libcanard_dsdl_compiler import run as dsdlc_run
  File "/vagrant/modules/DroneCAN/libcanard/dsdl_compiler/libcanard_dsdl_compiler/__init__.py", line 21, in <module>
    from uavcan import dsdl
ModuleNotFoundError: No module named 'uavcan' 
```
Appling this fix hepled:
https://github.com/UAVCAN/libuavcan/pull/318

I think that this repo should mirror this branch:
https://github.com/UAVCAN/libuavcan/tree/legacy-v0
or at least sync with it

**Comment by KarolNi** [comment]
I think https://github.com/dronecan/libcanard/commit/0a867526ed4fc572d0335a4a77501fe5400e997f closes it
